# Generated by Django 3.1.7 on 2021-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='first_name')),
                ('lastname', models.CharField(max_length=80, verbose_name='last_name')),
                ('email', models.EmailField(error_messages={'unique': 'The Email you entered is already present.'}, max_length=254, unique=True)),
                ('address', models.TextField(verbose_name='address')),
                ('dob', models.DateField(verbose_name='date_of_birth')),
                ('company', models.CharField(max_length=150, verbose_name='company name')),
                ('date_joined', models.DateField()),
                ('mobile', models.CharField(max_length=90, verbose_name='Mobile Number')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(max_length=80, verbose_name='first_name')),
                ('lastname', models.CharField(max_length=80, verbose_name='last_name')),
                ('email', models.EmailField(error_messages={'unique': 'The Email you entered is already present.'}, max_length=254, unique=True)),
                ('address', models.TextField(verbose_name='address')),
                ('dob', models.DateField(verbose_name='date_of_birth')),
                ('company', models.CharField(max_length=150, verbose_name='company name')),
                ('date_joined', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
    ]
