# Generated by Django 3.1.7 on 2021-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210320_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(auto_now_add=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(auto_now_add=True, verbose_name='date_of_birth'),
        ),
    ]
